apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
patches:
- path: patch-deployment.yaml
images:
- {}
- name: yeobi01/argocd-nextjs
  newTag: latest
