apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nextjs-deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: argocd-nextjs-container
          env:
            - name: NODE_ENV
              value: production
