apiVersion: v1
kind: Service
metadata:
  name: argocd-nextjs-service
  labels:
    app: argocd-nextjs-service
spec:
  selector:
    app: argocd-nextjs-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
